spring:
  application:
    name: demoProject

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: user
    password: password

  jpa:
    show-sql: true
    properties:
      hibernate:
        connection:
          pool_size: 30
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
    hibernate:
      ddl-auto: update

  h2:
    console:
      enabled: true
      path: /h2-console


  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

springdoc:

  api-docs:
    path: /api-docs

  show-actuator: false

  swagger-ui:
    show-extensions: true
    operations-sorter: method

server:
  port: 8080
