spring:
  application:
    name: demoProject

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

springdoc:

  api-docs:
    path: /api-docs

  show-actuator: false

  swagger-ui:
    show-extensions: true
    operations-sorter: method

server:
  port: 8080
